### ISSUE TITLE
You accidentally used Javascript on your web site, about not using Javascript

### ISSUE THREAD

**Issue by gooddadmike** [una/YouMightNotNeedJS#16]
I'm sure it was an oversight. You might not need javascript.

**Comment by una** [comment]
I hope opening this issue made you feel better

**Comment by gooddadmike** [comment]
I hope you took this with some humor. I am a fan of your stuff.
Specifically your open source goals and toolsday. Sorry If I was the
10,000th person to say it. I have mad respect for you.
