### ISSUE TITLE
Mobile Scrolling

### ISSUE THREAD

**Issue by una** [una/YouMightNotNeedJS#17]
https://twitter.com/Xavier_Ho/status/785962409353543681

**Comment by techtolentino** [comment]
I _think_ this might be able to be fixed by allowing overflow:

```
// index.styl, line 320

  .code
    flex 1
    margin 10px
    flex-basis 400px
    overflow: auto  // 👈

```

(I would submit a PR but I couldn't get it to run locally :/ )
