### ISSUE TITLE
For modal use :target instead of :focus

### ISSUE THREAD

**Issue by dominikwilkowski** [una/YouMightNotNeedJS#2]
Hi Una,

Love this effort. Thanks for putting some work into this.
My suggestion for the modal is to use `:target` instead of `:focus` as it also moves the focus to the open modal (important for a11y) and is arguably more stable.
A trick here is to use the close button to target the original open button as well so focus is also returned to the original element.
Happy to do a PR if you're interested.

Cheers

**Comment by r3nya** [comment]
Hi @una and @dominikwilkowski!

I totally agree with @dominikwilkowski.
Btw, I made a simple example for you http://codepen.io/r3nya/pen/pEKzyK
Please look. 

PS: Thanks for you idea. I love it. ❤️

**Comment by Haroenv** [comment]
related to #10, the version by @r3nya does work on Safari.

**Comment by r3nya** [comment]
Hey @Haroenv! 
It works on Safari 10 (macOS).

**Comment by Haroenv** [comment]
Yep, that's what I was saying. The version you posted does work, while the one on the site doesn't yet.

**Comment by r3nya** [comment]
@Haroenv oops, sorry … 

![](https://habrastorage.org/files/c56/14d/017/c5614d0172334195a651d5c770c2bca6.gif)
