### ISSUE TITLE
Enhance the a11y note

### ISSUE THREAD

**Issue by shadeed** [una/YouMightNotNeedJS#20]
When I first read the description, I skipped quickly to the demos and didn't notice the a11y note until I checked it again :D

I fiddled with this in the browser:
<img width="826" alt="screen shot 2016-10-12 at 6 33 06 am" src="https://cloud.githubusercontent.com/assets/8038659/19296598/77897328-9045-11e6-96b0-602d30cdc364.png">

Thoughts please? Will be happy to do a PR if all is good.

**Comment by una** [comment]
Resolved, thanks!
