### ISSUE TITLE
Add Picnic CSS

### ISSUE THREAD

**Issue by franciscop** [una/YouMightNotNeedJS#22]
I created [Picnic CSS](http://picnicss.com/) with many similar, pure css components. For instance, there are [Modals](http://picnicss.com/documentation#modal), [animated responsive Navs](http://picnicss.com/documentation#nav), [Tabs](http://picnicss.com/documentation#tabs) and [Tooltips](http://picnicss.com/documentation#tooltip)

**Comment by una** [comment]
I think some of these things like the tooltips would make great additions. Do you want to make a PR for those?
