### ISSUE TITLE
http://youmightnotneedjs.com/#color_picker not working under Safari 10.0

### ISSUE THREAD

**Issue by gerardo-navarro** [una/YouMightNotNeedJS#24]

**Comment by KittyGiraudel** [comment]
A simple solution would be to add a warning about limited browser support and link to CanIUse: http://caniuse.com/#feat=input-color.

**Comment by Haroenv** [comment]
It works on Safari 10+ on macOS, but not on iOS as a reference.

**Comment by una** [comment]
Resolved #50
